### ISSUE TITLE
Jim's materials are at https://github.com/jpivarski-talks/2024-06-20-uscms-princeton-tutorial

### ISSUE THREAD

**Issue by jpivarski** [iris-hep/uscms-idap-training#2]
I'm sorry that I missed the meeting. @ianna pointed me here and I didn't think there would be an issue with my lecture/worksheet/answers repo at https://github.com/jpivarski-talks/2024-06-20-uscms-princeton-tutorial. I thought that this was a GitHub org, and I would just fork my repo into that org.

But this is a GitHub repo: you're intending to merge all of the course materials into one repo? Mine won't work that way because I have a student worksheet in JupyterLite, which requires its own GitHub Actions deployment.

I've attached a link to my teaching materials in the normal way on Indico:

![image](https://github.com/iris-hep/uscms-idap-training/assets/1852447/e19df9db-65ad-4033-a025-db0c8d8b4d16)

Will this be good enough?

**Comment by alexander-held** [comment]
Hi Jim, I think that's fine. I'll start a readme with links and will also point to the fact that we link this on the agenda directly so navigation should be ok.
